version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: meu-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:  # Deixe em branco
      POSTGRES_DB: meu_banco_de_dados
    volumes:
      - ./data:/var/lib/postgresql/data
    command: ["postgres", "-c", "listen_addresses=*"]
